<?php
// ======================================================================
//             Designed by:    Eyasu Girma [Kiya]
//                 Mobile:     +251-913-078-029
//                 Email:      sendtokiya@gmail.com
//                 Facebook:   https://facebook.com/JoshKiyakoo
//                 LinkedIn:   https://linkedin.com/in/JoshKiyakoo
//                 Twitter:    https://twitter.com/JoshKiyakoo
//                 GitHub:     https://github.com/JoshKiyakoo
//                 Telegram:   https://t.me/JoshKiyakoo
// ======================================================================
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MembersDataSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        //
        DB::table('sfgbc_Members')
            ->insert(array(
                array("idMember"=> 1, "appellation"=>'Weyzerit', "firstName"=>'Saron', "middleName"=>'Kefelegn', "lastName"=>'Ashagre', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 2, "appellation"=>'Ato', "firstName"=>'Kaleb', "middleName"=>'Ameha', "lastName"=>'Yoseph', "gender"=>'Male', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 3, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_Eyasu_Girma_Zewde_Male_20211229_201244.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 4, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 5, "appellation"=>'Ato', "firstName"=>'Ermiyas', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_Ermiyas_Girma_Zewde_Male_20211229_203942.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 6, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Male', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 7, "appellation"=>'Weyzero', "firstName"=>'Mihiret', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 8, "appellation"=>'Ato', "firstName"=>'Esayas', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 9, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 10, "appellation"=>'Ato', "firstName"=>'Yonnas', "middleName"=>'Dibabu', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),

                array("idMember"=> 11, "appellation"=>'Ato', "firstName"=>'Abera', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 12, "appellation"=>'Weyzero', "firstName"=>'Asegedech', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),          
                array("idMember"=> 13, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 14, "appellation"=>'Ato', "firstName"=>'Lemma', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 15, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 16, "appellation"=>'Ato', "firstName"=>'Kebede', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 17, "appellation"=>'Ato', "firstName"=>'Feysel', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 18, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Male', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 19, "appellation"=>'Weyzero', "firstName"=>'Feven', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 20, "appellation"=>'Ato', "firstName"=>'Ermiyas', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),

                array("idMember"=> 21, "appellation"=>'Weyzero', "firstName"=>'Welela', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 22, "appellation"=>'Weyzero', "firstName"=>'Chalita', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 23, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 24, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Male', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 25, "appellation"=>'Weyzero', "firstName"=>'Koket', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 26, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 27, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Male', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 28, "appellation"=>'Ato', "firstName"=>'Samson', "middleName"=>'Seifu', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 29, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 30, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),

                array("idMember"=> 31, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 32, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 33, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Male', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 34, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 35, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 36, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 37, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 38, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 39, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 40, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),

                array("idMember"=> 41, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 42, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 43, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 44, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 45, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 46, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 47, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 48, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Male', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 49, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 50, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),

                array("idMember"=> 51, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 52, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 53, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 54, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 55, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 56, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 57, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 58, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 59, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 60, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),

                array("idMember"=> 61, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 62, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 63, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Male', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 64, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 65, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 66, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 67, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Male', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 68, "appellation"=>'Ato', "firstName"=>'Eyasu', "middleName"=>'Girma', "lastName"=>'Zewde', "gender"=>'Male', "birthDate"=>'1990-05-13', "civilStatus"=>'Never Married', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:35:50', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 69, "appellation"=>'Weyzero', "firstName"=>'Welansa', "middleName"=>'Zerihun', "lastName"=>'Aklilu', "gender"=>'Female', "birthDate"=>'1909-04-27', "civilStatus"=>'Devorced', "nationality"=>'Ethiopian', "status"=>'Active', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-06 15:17:25', "updated_at"=>NULL, "deleted_at"=>NULL),
                array("idMember"=> 70, "appellation"=>'Weyzero', "firstName"=>'Tsion', "middleName"=>'Gerawork', "lastName"=>'Derib', "gender"=>'Female', "birthDate"=>'1954-05-13', "civilStatus"=>'Legally Separated', "nationality"=>'Ethiopian', "status"=>'Inactive', "photograph"=>'storage/MRMS_MembersProfilePhoto/mrmsProfileImage_FName_MName_LName_Gender_YYYYMMDD_HHMMSS.jpg', "prefix"=>'SFGLC/', "suffix"=>'/21', "disabilityType"=>NULL, "memberRemark"=>NULL, "remember_token"=>NULL, "created_at"=>'2021-01-05 13:33:32', "updated_at"=>NULL, "deleted_at"=>NULL),
            )
        );
    }
}
