<?php
// ======================================================================
//             Designed by:    Eyasu Girma [Kiya]
//                 Mobile:     +251-913-078-029
//                 Email:      sendtokiya@gmail.com
//                 Facebook:   https://facebook.com/JoshKiyakoo
//                 LinkedIn:   https://linkedin.com/in/JoshKiyakoo
//                 Twitter:    https://twitter.com/JoshKiyakoo
//                 GitHub:     https://github.com/JoshKiyakoo
//                 Telegram:   https://t.me/JoshKiyakoo
// ======================================================================
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SystemLookupDataSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        //
        DB::table('sfgbc_Setting_LookupData')
            ->insert(array (
                // Lookup Data Values ||| List of Values
                array ('idLookupData'=>1,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Gender','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>2,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Civil Status','list_LookupDataDescription'=>'Root', 'list_LookupDataParent'=>0),
                array ('idLookupData'=>3,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Account Status','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>4,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Access Role','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>5,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Province','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>6,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Subcity','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>7,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Education Level','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>8,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Certification Level','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>9,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Organization Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>10,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Transfer Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>11,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Service Role','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>12,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Appellation','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>13,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Fellowship Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>14,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Relationship Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>15,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Funeral Coordinator','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>16,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Service Sector Main Category','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>17,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Service Sector Sub-Category','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>18,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Absence Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>19,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Payment Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>20,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Event Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>21,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Day of the Week','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>22,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Month of the Year','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>23,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Restructure Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>24,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'National Zone','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>25,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Local Zone','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>26,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Option','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>27,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Status','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>28,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Family Member Status','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>29,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Social Link Name','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>30,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'Province Type','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>31,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>32,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>33,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>34,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>35,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>36,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>37,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>38,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>39,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                array ('idLookupData'=>40,'list_LookupDataType'=>'Parent','list_LookupDataName'=>'','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>0),
                // Gender
                array ('idLookupData'=>41,'list_LookupDataType'=>'Gender','list_LookupDataName'=>'Male','list_LookupDataDescription'=>'ወንድ','list_LookupDataParent'=>1),
                array ('idLookupData'=>42,'list_LookupDataType'=>'Gender','list_LookupDataName'=>'Female','list_LookupDataDescription'=>'ሴት','list_LookupDataParent'=>1),
                // Civil Status
                array ('idLookupData'=>43,'list_LookupDataType'=>'Civil Status','list_LookupDataName'=>'Never Married','list_LookupDataDescription'=>'ያላገባ','list_LookupDataParent'=>2),
                array ('idLookupData'=>44,'list_LookupDataType'=>'Civil Status','list_LookupDataName'=>'Married','list_LookupDataDescription'=>'ያገባ','list_LookupDataParent'=>2),
                array ('idLookupData'=>45,'list_LookupDataType'=>'Civil Status','list_LookupDataName'=>'Divorced','list_LookupDataDescription'=>'ፈት','list_LookupDataParent'=>2),
                array ('idLookupData'=>46,'list_LookupDataType'=>'Civil Status','list_LookupDataName'=>'Widowed','list_LookupDataDescription'=>'መበለት','list_LookupDataParent'=>2),
                array ('idLookupData'=>47,'list_LookupDataType'=>'Civil Status','list_LookupDataName'=>'Legally Separated','list_LookupDataDescription'=>'በህግ የተለያዩ','list_LookupDataParent'=>2),
                // Account Status
                array ('idLookupData'=>48,'list_LookupDataType'=>'Account Status','list_LookupDataName'=>'Active','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>3),
                array ('idLookupData'=>49,'list_LookupDataType'=>'Account Status','list_LookupDataName'=>'Suspended','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>3),
                array ('idLookupData'=>50,'list_LookupDataType'=>'Account Status','list_LookupDataName'=>'Pending','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>3),
                array ('idLookupData'=>51,'list_LookupDataType'=>'Account Status','list_LookupDataName'=>'Rejected','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>3),
                array ('idLookupData'=>52,'list_LookupDataType'=>'Account Status','list_LookupDataName'=>'Blocked','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>3),
                // Access Role
                array ('idLookupData'=>53,'list_LookupDataType'=>'Access Role','list_LookupDataName'=>'Super Admin','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>4),
                array ('idLookupData'=>54,'list_LookupDataType'=>'Access Role','list_LookupDataName'=>'Administrator','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>4),
                array ('idLookupData'=>55,'list_LookupDataType'=>'Access Role','list_LookupDataName'=>'Manager','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>4),
                array ('idLookupData'=>56,'list_LookupDataType'=>'Access Role','list_LookupDataName'=>'Representative','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>4),
                array ('idLookupData'=>57,'list_LookupDataType'=>'Access Role','list_LookupDataName'=>'Coordinator','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>4),
                array ('idLookupData'=>58,'list_LookupDataType'=>'Access Role','list_LookupDataName'=>'Supervisor','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>4),
                array ('idLookupData'=>59,'list_LookupDataType'=>'Access Role','list_LookupDataName'=>'Member','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>4),
                // Province
                array ('idLookupData'=>60,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Addis Ababa','list_LookupDataDescription'=>'City Administration','list_LookupDataParent'=>5),
                array ('idLookupData'=>61,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Amhara','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>62,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Afar','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>63,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Beninshangul','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>64,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Dire Dawa','list_LookupDataDescription'=>'City Administration','list_LookupDataParent'=>5),
                array ('idLookupData'=>65,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Gambela','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>66,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Harar','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>67,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Oromiya','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>68,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Somali','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>69,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Southern Nations & Nationalities','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>70,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Tigray','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>71,'list_LookupDataType'=>'Province','list_LookupDataName'=>'Sidama','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                array ('idLookupData'=>72,'list_LookupDataType'=>'Province','list_LookupDataName'=>'South West','list_LookupDataDescription'=>'Regional State','list_LookupDataParent'=>5),
                // Subcity
                array ('idLookupData'=>73,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Addis Ketema','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>74,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Akaki Kality','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>75,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Arada','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>76,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Bole','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>77,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Gulele','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>78,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Kirkos','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>79,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Kolfe Keraniyo','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>80,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Lideta','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>81,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Nifas Silk Lafto','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>82,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Yeka','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>83,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Lemmi Kura','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                array ('idLookupData'=>84,'list_LookupDataType'=>'Subcity','list_LookupDataName'=>'Undefined','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>6),
                // Education Level
                array ('idLookupData'=>85,'list_LookupDataType'=>'Education Level','list_LookupDataName'=>'Univeristy | College','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>7),
                array ('idLookupData'=>86,'list_LookupDataType'=>'Education Level','list_LookupDataName'=>'Institution | Training Center','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>7),
                array ('idLookupData'=>87,'list_LookupDataType'=>'Education Level','list_LookupDataName'=>'Preparatory','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>7),
                array ('idLookupData'=>88,'list_LookupDataType'=>'Education Level','list_LookupDataName'=>'High School','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>7),
                array ('idLookupData'=>89,'list_LookupDataType'=>'Education Level','list_LookupDataName'=>'Secondary School','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>7),
                array ('idLookupData'=>90,'list_LookupDataType'=>'Education Level','list_LookupDataName'=>'Elementary School','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>7),
                array ('idLookupData'=>91,'list_LookupDataType'=>'Education Level','list_LookupDataName'=>'None','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>7),
                // Certification Level
                array ('idLookupData'=>92,'list_LookupDataType'=>'Certification Level','list_LookupDataName'=>'Doctorate (Ph.D.)','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>8),
                array ('idLookupData'=>93,'list_LookupDataType'=>'Certification Level','list_LookupDataName'=>'Masters Degree (MSc | MA)','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>8),
                array ('idLookupData'=>94,'list_LookupDataType'=>'Certification Level','list_LookupDataName'=>'Bachelor Degree (BSc | BA)','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>8),
                array ('idLookupData'=>95,'list_LookupDataType'=>'Certification Level','list_LookupDataName'=>'Diploma | TVET','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>8),
                array ('idLookupData'=>96,'list_LookupDataType'=>'Certification Level','list_LookupDataName'=>'Certificate','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>8),
                array ('idLookupData'=>97,'list_LookupDataType'=>'Certification Level','list_LookupDataName'=>'High School Diploma','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>8),
                array ('idLookupData'=>98,'list_LookupDataType'=>'Certification Level','list_LookupDataName'=>'Secondary School Certificate','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>8),
                array ('idLookupData'=>99,'list_LookupDataType'=>'Certification Level','list_LookupDataName'=>'None','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>8),
                // Organization Type
                array ('idLookupData'=>100,'list_LookupDataType'=>'Organization Type','list_LookupDataName'=>'Governmental Organization [GO]','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>9),
                array ('idLookupData'=>101,'list_LookupDataType'=>'Organization Type','list_LookupDataName'=>'Private Organization [PO]','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>9),
                array ('idLookupData'=>102,'list_LookupDataType'=>'Organization Type','list_LookupDataName'=>'Share Corporate Organization [SCO]','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>9),
                array ('idLookupData'=>103,'list_LookupDataType'=>'Organization Type','list_LookupDataName'=>'Non-Governmental Organization [NGO]','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>9),
                array ('idLookupData'=>104,'list_LookupDataType'=>'Organization Type','list_LookupDataName'=>'Association Organization [AO]','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>9),
                array ('idLookupData'=>105,'list_LookupDataType'=>'Organization Type','list_LookupDataName'=>'Self Employed [SE]','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>9),
                array ('idLookupData'=>106,'list_LookupDataType'=>'Organization Type','list_LookupDataName'=>'None [N/A]','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>9),
                // Transfer Type
                array ('idLookupData'=>107,'list_LookupDataType'=>'Transfer Type','list_LookupDataName'=>'Marriage','list_LookupDataDescription'=>'በጋብቻ','list_LookupDataParent'=>10),
                array ('idLookupData'=>108,'list_LookupDataType'=>'Transfer Type','list_LookupDataName'=>'Relocation','list_LookupDataDescription'=>'ስፍራ በመቀየር','list_LookupDataParent'=>10),
                array ('idLookupData'=>109,'list_LookupDataType'=>'Transfer Type','list_LookupDataName'=>'Spiritual Call','list_LookupDataDescription'=>'መንፈሳዊ ጥሪ','list_LookupDataParent'=>10),
                array ('idLookupData'=>110,'list_LookupDataType'=>'Transfer Type','list_LookupDataName'=>'Scandal','list_LookupDataDescription'=>'ቅይማት','list_LookupDataParent'=>10),
                array ('idLookupData'=>111,'list_LookupDataType'=>'Transfer Type','list_LookupDataName'=>'Other','list_LookupDataDescription'=>'ሌላ','list_LookupDataParent'=>10),
                // Service Role
                array ('idLookupData'=>112,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Member','list_LookupDataDescription'=>'አባል','list_LookupDataParent'=>11),
                array ('idLookupData'=>113,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Chairman','list_LookupDataDescription'=>'ሰብሳቢ','list_LookupDataParent'=>11),
                array ('idLookupData'=>114,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Vice Chairman','list_LookupDataDescription'=>' ምክትል ሰብሳቢ','list_LookupDataParent'=>11),
                array ('idLookupData'=>115,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Main Leader','list_LookupDataDescription'=>'ዋና መሪ','list_LookupDataParent'=>11),
                array ('idLookupData'=>116,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Assistant Leader','list_LookupDataDescription'=>'ረዳት መሪ','list_LookupDataParent'=>11),
                array ('idLookupData'=>117,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Accountant','list_LookupDataDescription'=>'ሒሳብ ሹም','list_LookupDataParent'=>11),
                array ('idLookupData'=>118,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Cashier','list_LookupDataDescription'=>'ገንዘብ ያዥ','list_LookupDataParent'=>11),
                array ('idLookupData'=>119,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Co-ordinator','list_LookupDataDescription'=>'አስተባባሪ','list_LookupDataParent'=>11),
                array ('idLookupData'=>120,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Secretary','list_LookupDataDescription'=>'ፀሐፊ','list_LookupDataParent'=>11),
                array ('idLookupData'=>121,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Supervisor','list_LookupDataDescription'=>'ተቆጣጣሪ','list_LookupDataParent'=>11),
                array ('idLookupData'=>122,'list_LookupDataType'=>'Service Role','list_LookupDataName'=>'Representative','list_LookupDataDescription'=>'ተጠሪ','list_LookupDataParent'=>11),
                // Appellation
                array ('idLookupData'=>123,'list_LookupDataType'=>'Appellation','list_LookupDataName'=>'Ato','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>12),
                array ('idLookupData'=>124,'list_LookupDataType'=>'Appellation','list_LookupDataName'=>'Weyzero','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>12),
                array ('idLookupData'=>125,'list_LookupDataType'=>'Appellation','list_LookupDataName'=>'Weyzerit','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>12),
                // Fellowship Type
                array ('idLookupData'=>126,'list_LookupDataType'=>'Fellowship Type','list_LookupDataName'=>'Home Cell Fellowship','list_LookupDataDescription'=>'Root','list_LookupDataParent'=>13),
                array ('idLookupData'=>127,'list_LookupDataType'=>'Fellowship Type','list_LookupDataName'=>'Youth Service Fellowship','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>13),
                array ('idLookupData'=>128,'list_LookupDataType'=>'Fellowship Type','list_LookupDataName'=>'Family Life Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>13),
                array ('idLookupData'=>129,'list_LookupDataType'=>'Fellowship Type','list_LookupDataName'=>'Children Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>13),
                array ('idLookupData'=>130,'list_LookupDataType'=>'Fellowship Type','list_LookupDataName'=>'Choir’s Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>13),
                array ('idLookupData'=>131,'list_LookupDataType'=>'Fellowship Type','list_LookupDataName'=>'Prayer Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>13),
                array ('idLookupData'=>132,'list_LookupDataType'=>'Fellowship Type','list_LookupDataName'=>'Deacons Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>13),
                array ('idLookupData'=>133,'list_LookupDataType'=>'Fellowship Type','list_LookupDataName'=>'Leaders Assembly','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>13),
                // Relationship Type
                array ('idLookupData'=>134,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Father','list_LookupDataDescription'=>'A male parent.','list_LookupDataParent'=>14),
                array ('idLookupData'=>135,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Mother','list_LookupDataDescription'=>'A female parent.','list_LookupDataParent'=>14),
                array ('idLookupData'=>136,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Husband','list_LookupDataDescription'=>'The man a woman is married to.','list_LookupDataParent'=>14),
                array ('idLookupData'=>137,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Wife','list_LookupDataDescription'=>'The woman a man is married to.','list_LookupDataParent'=>14),
                array ('idLookupData'=>138,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Son','list_LookupDataDescription'=>'Your male child.','list_LookupDataParent'=>14),
                array ('idLookupData'=>139,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Daughter','list_LookupDataDescription'=>'Your female child.','list_LookupDataParent'=>14),
                array ('idLookupData'=>140,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Brother','list_LookupDataDescription'=>'A man or boy with the same parents as another person.','list_LookupDataParent'=>14),
                array ('idLookupData'=>141,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Sister','list_LookupDataDescription'=>'A girl or woman who has the same parents as another person.','list_LookupDataParent'=>14),
                array ('idLookupData'=>142,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Child','list_LookupDataDescription'=>'A boy or girl from the time of birth until he or she is an adult, or a son or daughter of any age.','list_LookupDataParent'=>14),
                array ('idLookupData'=>143,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Aunt','list_LookupDataDescription'=>'The sister of someone\'s father or mother, or the wife of someone\'s uncle.','list_LookupDataParent'=>14),
                array ('idLookupData'=>144,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Cousin','list_LookupDataDescription'=>'A child of a person\'s aunt or uncle, or, more generally, a distant (= not close) relation.','list_LookupDataParent'=>14),
                array ('idLookupData'=>145,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Relative','list_LookupDataDescription'=>'A member of your family.','list_LookupDataParent'=>14),
                array ('idLookupData'=>146,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Uncle','list_LookupDataDescription'=>'The brother of someone\'s mother or father, or the husband of someone\'s aunt.','list_LookupDataParent'=>14),
                array ('idLookupData'=>147,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Dependent','list_LookupDataDescription'=>'Someone who depends on you for financial support, such as a child or family member who does not work.','list_LookupDataParent'=>14),
                array ('idLookupData'=>148,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'First Cousin','list_LookupDataDescription'=>'A child of your aunt or uncle.','list_LookupDataParent'=>14),
                array ('idLookupData'=>149,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Friend','list_LookupDataDescription'=>'A person who you know well and who you like a lot, but who is usually not a member of your family.','list_LookupDataParent'=>14),
                array ('idLookupData'=>150,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Grandchild','list_LookupDataDescription'=>'The child of a person\'s son or daughter.','list_LookupDataParent'=>14),
                array ('idLookupData'=>151,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Granddaughter','list_LookupDataDescription'=>'The daughter of a person\'s son or daughter.','list_LookupDataParent'=>14),
                array ('idLookupData'=>152,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Grandfather','list_LookupDataDescription'=>'The father of a person\'s mother or father.','list_LookupDataParent'=>14),
                array ('idLookupData'=>153,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Grandmother','list_LookupDataDescription'=>'The mother of a person\'s mother or father','list_LookupDataParent'=>14),
                array ('idLookupData'=>154,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Grandparent','list_LookupDataDescription'=>'The father or mother of a person\'s father or mother.','list_LookupDataParent'=>14),
                array ('idLookupData'=>155,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Grandson','list_LookupDataDescription'=>'The son of a person\'s son or daughter.','list_LookupDataParent'=>14),
                array ('idLookupData'=>156,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Great-Grandfather','list_LookupDataDescription'=>'The grandfather of one of your parents.','list_LookupDataParent'=>14),
                array ('idLookupData'=>157,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Great-Grandmother','list_LookupDataDescription'=>'The grandmother of one of your parents.','list_LookupDataParent'=>14),
                array ('idLookupData'=>158,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Grate-Grandson','list_LookupDataDescription'=>'The grandson of your child.','list_LookupDataParent'=>14),
                array ('idLookupData'=>159,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Grate-Granddaughter','list_LookupDataDescription'=>'The granddaughter of your child.','list_LookupDataParent'=>14),
                array ('idLookupData'=>160,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Half-Brother','list_LookupDataDescription'=>'A brother who is the son of only one of your parents.','list_LookupDataParent'=>14),
                array ('idLookupData'=>161,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Half-Sister','list_LookupDataDescription'=>'A sister who is the daughter of only one of your parents','list_LookupDataParent'=>14),
                array ('idLookupData'=>162,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Maiden Aunt','list_LookupDataDescription'=>'An aunt who is not married and is no longer young','list_LookupDataParent'=>14),
                array ('idLookupData'=>163,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Maternal','list_LookupDataDescription'=>'Related to a mother\'s side of the family.','list_LookupDataParent'=>14),
                array ('idLookupData'=>164,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Nephew','list_LookupDataDescription'=>'A son of your sister or brother, or a son of the sister or brother of your husband or wife.','list_LookupDataParent'=>14),
                array ('idLookupData'=>165,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Next Of Kin','list_LookupDataDescription'=>'The person or group of people you are most closely related to.','list_LookupDataParent'=>14),
                array ('idLookupData'=>166,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Niece','list_LookupDataDescription'=>'A daughter of your brother or sister, or a daughter of your husband\'s or wife\'s brother or sister.','list_LookupDataParent'=>14),
                array ('idLookupData'=>167,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Paternal','list_LookupDataDescription'=>'Of or like a father.','list_LookupDataParent'=>14),
                array ('idLookupData'=>168,'list_LookupDataType'=>'Relationship Type','list_LookupDataName'=>'Second Cousin','list_LookupDataDescription'=>'Any person who is a child of a cousin of your mother or father.','list_LookupDataParent'=>14),
                // Funeral Coordinator
                array ('idLookupData'=>169,'list_LookupDataType'=>'Funeral Coordinator','list_LookupDataName'=>'Family | Relative | Keen','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>15),
                array ('idLookupData'=>170,'list_LookupDataType'=>'Funeral Coordinator','list_LookupDataName'=>'Church','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>15),
                array ('idLookupData'=>171,'list_LookupDataType'=>'Funeral Coordinator','list_LookupDataName'=>'Municipality','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>15),
                // Service Sector Main Category
                array ('idLookupData'=>172,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Evangelism and Testimonials Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>173,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Doctrine and Discipleship Education','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>174,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Home Fellowship','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>175,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Youth’s Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>176,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Children’s Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>177,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Marriage and Family Life Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>178,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Prayer Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),    
                array ('idLookupData'=>179,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Deliverance Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>180,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Education and Training','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>181,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Choir Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>182,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Fund Raising Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>183,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Nethinims Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>184,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Counseling and Followup Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>185,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Elders’ Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>186,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Worship Leaders Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>187,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Sound System and Players Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>188,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Deacons Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>189,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Evangelist Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>190,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Full Timers\' Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                array ('idLookupData'=>191,'list_LookupDataType'=>'Service Sector Main Category','list_LookupDataName'=>'Information Technology and Documentation Service','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>16),
                // Service Sector Sub-Category
                array ('idLookupData'=>192,'list_LookupDataType'=>'Service Sector Sub-Category','list_LookupDataName'=>'Sub Category 1','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>17),
                array ('idLookupData'=>193,'list_LookupDataType'=>'Service Sector Sub-Category','list_LookupDataName'=>'Sub Category 2','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>17),
                array ('idLookupData'=>194,'list_LookupDataType'=>'Service Sector Sub-Category','list_LookupDataName'=>'Sub Category 3','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>17),
                // Absence Type
                array ('idLookupData'=>195,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Present','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>196,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Absent','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>197,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Vacation','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>198,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Permission','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>199,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Sickness','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>200,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Maternity','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>201,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Education','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>202,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Training','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>203,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Exam','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                array ('idLookupData'=>204,'list_LookupDataType'=>'Absence Type','list_LookupDataName'=>'Other','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>18),
                // Payment Type
                array ('idLookupData'=>205,'list_LookupDataType'=>'Payment Type','list_LookupDataName'=>'Cash','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>19),
                array ('idLookupData'=>206,'list_LookupDataType'=>'Payment Type','list_LookupDataName'=>'Check','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>19),
                array ('idLookupData'=>207,'list_LookupDataType'=>'Payment Type','list_LookupDataName'=>'CPO','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>19),
                array ('idLookupData'=>208,'list_LookupDataType'=>'Payment Type','list_LookupDataName'=>'Bank Transfer','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>19),
                array ('idLookupData'=>209,'list_LookupDataType'=>'Payment Type','list_LookupDataName'=>'Other','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>19),
                // Event Type
                array ('idLookupData'=>210,'list_LookupDataType'=>'Event Type','list_LookupDataName'=>'Active','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>20),
                array ('idLookupData'=>211,'list_LookupDataType'=>'Event Type','list_LookupDataName'=>'Canceled','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>20),
                array ('idLookupData'=>212,'list_LookupDataType'=>'Event Type','list_LookupDataName'=>'Postponed','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>20),
                array ('idLookupData'=>213,'list_LookupDataType'=>'Event Type','list_LookupDataName'=>'Frozen','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>20),
                array ('idLookupData'=>214,'list_LookupDataType'=>'Event Type','list_LookupDataName'=>'Inactive','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>20),
                array ('idLookupData'=>215,'list_LookupDataType'=>'Event Type','list_LookupDataName'=>'Running','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>20),
                // Day of the Week
                array ('idLookupData'=>216,'list_LookupDataType'=>'Day of the Week','list_LookupDataName'=>'Sunday','list_LookupDataDescription'=>'እሑድ','list_LookupDataParent'=>21),
                array ('idLookupData'=>217,'list_LookupDataType'=>'Day of the Week','list_LookupDataName'=>'Monday','list_LookupDataDescription'=>'ሰኞ','list_LookupDataParent'=>21),
                array ('idLookupData'=>218,'list_LookupDataType'=>'Day of the Week','list_LookupDataName'=>'Tuesday','list_LookupDataDescription'=>'ማክሰኞ','list_LookupDataParent'=>21),
                array ('idLookupData'=>219,'list_LookupDataType'=>'Day of the Week','list_LookupDataName'=>'Wednesday','list_LookupDataDescription'=>'ረቡዕ','list_LookupDataParent'=>21),
                array ('idLookupData'=>220,'list_LookupDataType'=>'Day of the Week','list_LookupDataName'=>'Thursday','list_LookupDataDescription'=>'ሐሙስ','list_LookupDataParent'=>21),
                array ('idLookupData'=>221,'list_LookupDataType'=>'Day of the Week','list_LookupDataName'=>'Friday','list_LookupDataDescription'=>'ዓርብ','list_LookupDataParent'=>21),
                array ('idLookupData'=>222,'list_LookupDataType'=>'Day of the Week','list_LookupDataName'=>'Saturday','list_LookupDataDescription'=>'ቅዳሜ','list_LookupDataParent'=>21),
                // Month of the Year
                array ('idLookupData'=>223,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'September','list_LookupDataDescription'=>'መስከረም','list_LookupDataParent'=>22),
                array ('idLookupData'=>224,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'October','list_LookupDataDescription'=>'ጥቅምት','list_LookupDataParent'=>22),
                array ('idLookupData'=>225,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'November','list_LookupDataDescription'=>'ህዳር','list_LookupDataParent'=>22),
                array ('idLookupData'=>226,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'December','list_LookupDataDescription'=>'ታህሣሥ','list_LookupDataParent'=>22),
                array ('idLookupData'=>227,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'January','list_LookupDataDescription'=>'ጥር','list_LookupDataParent'=>22),
                array ('idLookupData'=>228,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'February','list_LookupDataDescription'=>'የካቲት','list_LookupDataParent'=>22),
                array ('idLookupData'=>229,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'March','list_LookupDataDescription'=>'መጋቢት','list_LookupDataParent'=>22),
                array ('idLookupData'=>230,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'April','list_LookupDataDescription'=>'ሚያዝያ','list_LookupDataParent'=>22),
                array ('idLookupData'=>231,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'May','list_LookupDataDescription'=>'ግንቦት','list_LookupDataParent'=>22),
                array ('idLookupData'=>232,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'June','list_LookupDataDescription'=>'ሰኔ','list_LookupDataParent'=>22),
                array ('idLookupData'=>233,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'July','list_LookupDataDescription'=>'ሐምሌ','list_LookupDataParent'=>22),
                array ('idLookupData'=>234,'list_LookupDataType'=>'Month of the Year','list_LookupDataName'=>'August','list_LookupDataDescription'=>'ነሐሴ-ጳጉሜን','list_LookupDataParent'=>22),
                // Restructure Type
                array ('idLookupData'=>235,'list_LookupDataType'=>'Restructure Type','list_LookupDataName'=>'New','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>23),
                array ('idLookupData'=>236,'list_LookupDataType'=>'Restructure Type','list_LookupDataName'=>'Folded','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>23),
                array ('idLookupData'=>237,'list_LookupDataType'=>'Restructure Type','list_LookupDataName'=>'Separation','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>23),
                array ('idLookupData'=>238,'list_LookupDataType'=>'Restructure Type','list_LookupDataName'=>'Termination','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>23),
                array ('idLookupData'=>239,'list_LookupDataType'=>'Restructure Type','list_LookupDataName'=>'Uncertain','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>23),
                // National Zone
                array ('idLookupData'=>240,'list_LookupDataType'=>'National Zone','list_LookupDataName'=>'Central Katana','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>24),
                array ('idLookupData'=>241,'list_LookupDataType'=>'National Zone','list_LookupDataName'=>'Northern Katana','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>24),
                array ('idLookupData'=>242,'list_LookupDataType'=>'National Zone','list_LookupDataName'=>'Southern Katana','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>24),
                array ('idLookupData'=>243,'list_LookupDataType'=>'National Zone','list_LookupDataName'=>'Eastern Katana','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>24),
                array ('idLookupData'=>244,'list_LookupDataType'=>'National Zone','list_LookupDataName'=>'Western Katana','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>24),
                // Local Zone
                array ('idLookupData'=>245,'list_LookupDataType'=>'Local Zone','list_LookupDataName'=>'Addisu Gebeya','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>25),
                array ('idLookupData'=>246,'list_LookupDataType'=>'Local Zone','list_LookupDataName'=>'Piassa','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>25),
                array ('idLookupData'=>247,'list_LookupDataType'=>'Local Zone','list_LookupDataName'=>'Sholla','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>25),
                array ('idLookupData'=>248,'list_LookupDataType'=>'Local Zone','list_LookupDataName'=>'Semien Mazegaja','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>25),
                array ('idLookupData'=>249,'list_LookupDataType'=>'Local Zone','list_LookupDataName'=>'Kechene','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>25),
                // Option
                array ('idLookupData'=>250,'list_LookupDataType'=>'Option','list_LookupDataName'=>'Yes','list_LookupDataDescription'=>'አዎ','list_LookupDataParent'=>26),
                array ('idLookupData'=>251,'list_LookupDataType'=>'Option','list_LookupDataName'=>'No','list_LookupDataDescription'=>'አይ','list_LookupDataParent'=>26),
                // Status
                array ('idLookupData'=>252,'list_LookupDataType'=>'Status','list_LookupDataName'=>'Active','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>27),
                array ('idLookupData'=>253,'list_LookupDataType'=>'Status','list_LookupDataName'=>'Inactive','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>27),
                // Family Member Status
                array ('idLookupData'=>254,'list_LookupDataType'=>'Family Member Status','list_LookupDataName'=>'Member','list_LookupDataDescription'=>'አባል','list_LookupDataParent'=>28),
                array ('idLookupData'=>255,'list_LookupDataType'=>'Family Member Status','list_LookupDataName'=>'Believer','list_LookupDataDescription'=>'አማኝ','list_LookupDataParent'=>28),
                array ('idLookupData'=>256,'list_LookupDataType'=>'Family Member Status','list_LookupDataName'=>'None Believer','list_LookupDataDescription'=>'አማኝ ያልሆነ','list_LookupDataParent'=>28),
                // Social Link Name
                array ('idLookupData'=>257,'list_LookupDataType'=>'Social Link Name','list_LookupDataName'=>'Facebook','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>29),
                array ('idLookupData'=>258,'list_LookupDataType'=>'Social Link Name','list_LookupDataName'=>'Telegram','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>29),
                array ('idLookupData'=>259,'list_LookupDataType'=>'Social Link Name','list_LookupDataName'=>'Youtube','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>29),
                array ('idLookupData'=>260,'list_LookupDataType'=>'Social Link Name','list_LookupDataName'=>'Twitter','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>29),
                array ('idLookupData'=>261,'list_LookupDataType'=>'Social Link Name','list_LookupDataName'=>'LinkedIn','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>29),
                array ('idLookupData'=>262,'list_LookupDataType'=>'Social Link Name','list_LookupDataName'=>'Instagram','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>29),
                array ('idLookupData'=>263,'list_LookupDataType'=>'Social Link Name','list_LookupDataName'=>'Whatsapp','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>29),
                array ('idLookupData'=>264,'list_LookupDataType'=>'Social Link Name','list_LookupDataName'=>'Skype','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>29),
                // Province Type
                array ('idLookupData'=>265,'list_LookupDataType'=>'Province Type','list_LookupDataName'=>'Regional State','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>30),
                array ('idLookupData'=>266,'list_LookupDataType'=>'Province Type','list_LookupDataName'=>'City Administration','list_LookupDataDescription'=>NULL,'list_LookupDataParent'=>30)
            )
        );
    }
}
